// Generated by github.com/davyxu/cellnet/internal-gen
// DO NOT EDIT!
package InternalMessage

import (
	"github.com/davyxu/cellnet"
	_ "github.com/Blizzardx/GoGameServer/Core/Modules/codec/msgpack"
	"reflect"
	"fmt"
	"github.com/davyxu/cellnet/codec"
)

func (self *InternalMsg) String() string           { return fmt.Sprintf("%+v", *self) }
func (self *RegisterGameServerMsg) String() string { return fmt.Sprintf("%+v", *self) }

func init() {

	cellnet.RegisterMessageMeta(&cellnet.MessageMeta{
		Codec: codec.MustGetCodec("msgpack"),
		Type:  reflect.TypeOf((*InternalMsg)(nil)).Elem(),
		ID:    60068,
	})

	cellnet.RegisterMessageMeta(&cellnet.MessageMeta{
		Codec: codec.MustGetCodec("msgpack"),
		Type:  reflect.TypeOf((*RegisterGameServerMsg)(nil)).Elem(),
		ID:    9053,
	})

}
